### PR TITLE
Fix margins and spacing

### LINKED ISSUE #91: Excessive top white-space and too large heading sizes on mobile
## Describe the bug
On mobile devices with lower resolution (such as phones) there is excessive white space above the page headings. It is most noticable on the "How to share code" page. Less critical but also noticable: The page heading fontsizes also appears too large on mobile.

## Expected behavior
The excessive white space should not be present on mobile devices. Page headings should be sized correctly for mobile devices.

## To Reproduce
1. Use a typical phone browser.
2. Click on 'Sharing Code' (where the effect is biggest).
3. See the page heading too far down on the page and heading font size is very large.

### Screenshots
Screenshot_20220212-072517_Chrome

## Additional context
This is likely related to hardcoded values for margin and/or padding. Switching to a responsive setting for those may be an option. The bulma spacing helpers use rem which may be one approach to solving this. The page headings (especially the top one) also appears larger than ideal on mobile. An adjustment to responsive font sizes can perhaps also be included in the fix.

### PR DESCRIPTION
**Pull request by mikejoh12**
## What issue is this solving?

Closes #91

### Description
This fixes excessive and uneven margins that previously appeared at the top of the pages on mobile devices. It makes h1 and h2 headings responsive so that they don't take up the entire screen-width on mobile devices.

## Any helpful knowledge/context for the reviewer?
Please test on various browsers/devices.

### Please make sure you've attempted to meet the following coding standards

- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by yingmo55 — APPROVED** [review]
Looks good to me!

**Review by lyallstewart — APPROVED** [review]
LGTM!

**Review by Victoria-DR — COMMENTED** [review]
The changes made to the spacing and text size look good, thanks! Just a couple of other things I noticed that could be fixed too in this PR:

 * The spacing above and below the headers isn't the same. Looking at the header section on the Server Staff and FAQ pages on mobile, we could use a little more padding below the header.
 * Some padding should be added on the left and right of the text against the beige background right under the headers on the Contact Us, Sharing Code, and getting help pages. Currently, the text extends to the walls of the screen.

**Review by Victoria-DR — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
