### PR TITLE
Fix close hamburger menu on mousedown

### LINKED ISSUE #110: Hamburger menu does not close when pressing anywhere outside of it
The mobile hamburger menu only closes when pressing the X. It is generally expected for most websites that pressing anywhere outside of a hamburger-menu should close it.

### PR DESCRIPTION
**Pull request by TobiasDemoor**
## What issue is this solving?

Closes #110 

### Description

Added event listener on mousedown to setIsActive(false).

## Any helpful knowledge/context for the reviewer?

- Any new dependencies to install? No
- Any special requirements to test? No

### Feelings gif (optional)

What gif best describes your feeling working on this issue? https://giphy.com/
feeling gif

### Please make sure you've attempted to meet the following coding standards

- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by mikejoh12 — COMMENTED** [review]
Nice work! Just some minor comments. Since this is the first custom hook for the project perhaps we can create a directory for hooks and relocate the hook to a file in /src/hooks. Then it can be imported from there into Header.js.

Also, to make it more clear what the hook does the name could be changed from useOutsideCallback to something like useCloseBurgerMenu.

**Comment by TobiasDemoor** [comment]
@mikejoh12 there you go. Please tell me if there is anything else that needs changes

**Review by mikejoh12 — APPROVED** [review]

**Review by lyallstewart — APPROVED** [review]
Works perfectly, thanks @TobiasDemoor!

**Review by Victoria-DR — APPROVED** [review]
LGTM

**Pull request merged**
