### PR TITLE
Update staff bio page

### PR DESCRIPTION
**Pull request by lyallstewart**
## What issue is this solving?
No formal issue.

### Description
Small PR with a handful of updates to the staff page:
- Updates the profile pictures of 8-bit and UnseenCode
- Slightly changes the card size as Christo's name was a big longer so it was messing with the centering
- Moves me to the mod section (yay 🎉)

## Any helpful knowledge/context for the reviewer?

- Any new dependencies to install? ❌ 
- Any special requirements to test? ❌ 

### Please make sure you've attempted to meet the following coding standards

- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by Shaylin-8bit — APPROVED** [review]
LGTM!! 👍

**Review by Victoria-DR — APPROVED** [review]
While we're here, would you mind changing over my name from Victoria_DR to Victoria-DR too? Thanks! 😅

**Comment by Victoria-DR** [comment]
> Ooops, my bad there Victoria, must have misread that the first time around! 😅

Haha no, you got it right the first time! I recently changed it so that it could be consistent with my GH username.

**Comment by lyallstewart** [comment]
If no-one has any more requested changes would @Victoria-DR or @aedwardg mind merging this?

**Pull request merged**
