### PR TITLE
Added the codecademy logo as a favicon to current pages

### PR DESCRIPTION
**Pull request by lyallstewart**
### Description
Quick PR that adds the Codecademy Mini logo as a favicon for the site (on all currently added pages):
image

## Any helpful knowledge/context for the reviewer?

- Any new dependencies to install? ❌ 
- Any special requirements to test? ❌ 

### Please make sure you've attempted to meet the following coding standards

- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by Victoria-DR — CHANGES_REQUESTED** [review]
The link tag only needs to be inserted once in index.html so the other tags can be removed from the other files. Also, I think the CC logo got an update (navy background, white image, flatter logo) and I think it'd be better to use the updated one to match our server icon.

**Comment by lyallstewart** [comment]
Hi @Victoria-DR,
Thanks for the review! I'll push up the different logo in a minute - is it this one you mean?: 
cc2
I tried to only have the icon `<link>` tag in index.html but then it didn't display on any of the other pages

**Comment by Victoria-DR** [comment]
@lyallstewart 
Yep, that's the new logo. I think you're supposed to be able to see the favicon on all pages as long as you add the favicon file to the root directory. However, I tried it myself and it isn't working. I guess we should use your original code then, with the link tags on every page.

**Comment by lyallstewart** [comment]
@Victoria-DR 
Ok, sounds good - I've just changed the logo to the newer image:
image

**Review by Victoria-DR — APPROVED** [review]
Awesome, thanks!

**Comment by lyallstewart** [comment]
Thanks @Victoria-DR,
Would you mind merging - I'm not able to 😄

**Pull request merged**
