### PR TITLE
Added `StaffCard` component

### LINKED ISSUE #67: Add `<StaffCard />` component
## Purpose
Replace the current div with a staff page component, this will also make it easier to re-add the modals for the staff bios.

### Is your feature request related to a problem? Please describe.
At the moment we have a div for the staff cards, it would better follow standard React practice to have a seperate component for this instead. It will also help with adding modals as the logic for showing/hiding each modal can be handled on a per-component basis.

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] Staff card should be a new React component
- [ ] Data should be passed in via props.

### PR DESCRIPTION
**Pull request by lyallstewart**
## What issue is this solving?

Closes #67 

### Description
To modularise our code a little and to make it *much* easier to add modals later (as the code for handling when to show or hide each modal can be handled on a per-component basis). The divs containing each staff card now have a `<StaffCard />` component with the appropriate data passed as props.

## Any helpful knowledge/context for the reviewer?

- Any new dependencies to install? ❌ 
- Any special requirements to test? ❌

### Please make sure you've attempted to meet the following coding standards

- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

**Comment by mikejoh12** [comment]
Getting a console warning: Warning: StaffCard: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop

Proposed fix: Remove references to key prop in StaffCard component. Remove from the prop destructuring and inside the <div> in StaffCard. This removes the console warning.

Also, lint alert for: 
img elements must have an alt prop, either with meaningful text, or an empty string for decorative images. Perhaps we can add an alt prop to the  tag in <StaffCard />. Either empty string or perhaps just use the name prop for the alt description.

**Comment by lyallstewart** [comment]
Thanks @mikejoh12! That should fix both 🙂

**Review by mikejoh12 — APPROVED** [review]

**Review by Victoria-DR — APPROVED** [review]
Looks good!

**Comment by lyallstewart** [comment]
I think two approving reviews is a good target for a PR being accepted so I'll go ahead and merge this now.

**Pull request merged**
